name: Publish

on:
  push:
    ## Run on tags starting with `v*`
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish:
    name: Publish for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: hyperdrive-gateway-linux-$tag
            asset_name: dist/hyperdrive-gateway-linux
            to_run: npm run build-linux
          - os: windows-latest
            artifact_name: hyperdrive-gateway-windows-$tag.exe
            asset_name: dist/hyperdrive-gateway-windows.exe
            to_run: npm run build-windows
          - os: macos-latest
            artifact_name: hyperdrive-gateway-mac-$tag
            asset_name: dist/hyperdrive-gateway-mac
            to_run: npm run build-mac

    steps:
    - uses: actions/checkout@v2
    - name: Setup node
      uses: actions/setup-node@v2
      with:
        node-version: 14
    - name: Build
      run: ${{ matrix.to_run }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
